name: Build Android APK
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    permissions: # Requis pour créer une release
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Cache Expo local build
        uses: actions/cache@v4
        with:
          path: ~/.eas-build-local
          key: eas-local-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: eas-local-${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build APK (Local mode in CI)
        run: eas build --platform android --profile preview --non-interactive --local
        env:
          STITCH_API_KEY: ${{ secrets.STITCH_API_KEY }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          EXPO_PUBLIC_TMDB_API_KEY: ${{ secrets.EXPO_PUBLIC_TMDB_API_KEY }}
          EXPO_PUBLIC_TMDB_BASE_URL: ${{ secrets.EXPO_PUBLIC_TMDB_BASE_URL }}
          EXPO_PUBLIC_TMDB_IMAGE_BASE_URL: ${{ secrets.EXPO_PUBLIC_TMDB_IMAGE_BASE_URL }}

      - name: Get APK Filename
        id: get-apk
        run: echo "path=$(ls *.apk)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release CineMatch v${{ github.run_number }}
          files: ${{ steps.get-apk.outputs.path }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
